driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8090}]
    - ["forwarded_port", {guest: 8080, host: 9090}]

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[lamp::default]
    attributes:
